name = "line-harness"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

account_id = "c54668a1278021e070d33ee893712188"

[assets]
directory = "dist/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "2400952d-86e1-4c02-b8de-05c83fdb2bf4"

[triggers]
crons = ["*/5 * * * *"]
